# Generated by Django 4.2.7 on 2024-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_type', models.CharField(choices=[('S', 'Student'), ('E', 'Employee'), ('Ex', 'Extern')], max_length=2)),
                ('matriculation', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
